### ISSUE TITLE
Quick start guide fails at create-index-from-file step

### ISSUE THREAD

**Issue by schlarpc** [izihawa/summa#162]
The schema specified in the quick start guide has a `default_fields` element which blows up in the current version of `aiosumma`. It looks like this was removed in 164310a2, so the docs should probably be updated to match.

```
$ summa-cli localhost:8082 - create-index-from-file ~/summa/schema.yaml
SERVER_RESPONDED:
Traceback (most recent call last):
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 577, in _GetFieldByName
    return message_descriptor.fields_by_name[field_name]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'default_fields'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nix/store/7hxdkn32a2qqvacpi4fh7sr73yigv75j-python3.11-aiosumma-2.44.1/bin/.summa-cli-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/aiosumma/cli.py", line 25, in main
    fire.Fire(client_cli, name='summa-client')
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/fire/core.py", line 689, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ng1c2jqy48p1x33j1qyg0n5anhfv31g0-python3-3.11.4/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/aiogrpcclient/base.py", line 94, in exposing_wrapper
    result = await f
             ^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/aiogrpcclient/base.py", line 39, in inner
    return await method(**data)
           ^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/aiosumma/client.py", line 242, in create_index
    index_service_pb.CreateIndexRequest(
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 548, in init
    new_val = field.message_type._concrete_class(**field_value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 516, in init
    field = _GetFieldByName(message_descriptor, field_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/l3xw4yisgv61a1lrg2rcxm2xjsjs9srx-python3-3.11.4-env/lib/python3.11/site-packages/google/protobuf/internal/python_message.py", line 579, in _GetFieldByName
    raise ValueError('Protocol message %s has no "%s" field.' %
ValueError: Protocol message IndexAttributes has no "default_fields" field.
```

**Comment by ppodolsky** [comment]
I need to add tests for these docs, they get out of sync often... Thank you!
